FROM ruby:2.7.1

RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add - \
    && echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list \
    && apt-get update -qq \
    && apt-get install -y nodejs yarn

# 最新版のlockファイルは/tmpに保存される
WORKDIR /tmp
COPY Gemfile /tmp
COPY Gemfile.lock /tmp

# bundler入りのイメージを作成する
RUN gem install bundler:2.1.4
RUN bundle install

WORKDIR /app
RUN rm -rf node_modules
RUN yarn install --check-files
COPY . /app

COPY entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["/usr/bin/entrypoint.sh"]
EXPOSE 3000

CMD ["rails", "server", "-b", "0.0.0.0"]